"""Constants for the Jackery Diagnostics integration."""

from __future__ import annotations

from pathlib import Path

DOMAIN = "jackery_diagnostics"
INTEGRATION_VERSION = "1.9"
BASE_URL = "https://iot.jackeryapp.com"
LOGIN_ENDPOINT = "/v1/auth/login"
DEVICE_LIST_ENDPOINT = "/v1/device/bind/list"
RESULTS_PATH = Path("/config/jackery_diagnostics_results.json")
NOTIFICATION_ID = "jackery_diagnostics_results"
NOTIFICATION_TITLE = "Jackery Diagnostics Results"
REQUEST_TIMEOUT = 15
MQTT_CAPTURE_SECONDS = 30
AES_KEY = b"1234567890123456"
RSA_PUBLIC_KEY = (
    "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCVmzgJy/4XolxPnkfu32YtJqYGFLYq"
    "f9/rnVgURJED+8J9J3Pccd6+9L97/+7COZE5OkejsgOkqeLNC9C3r5mhpE4zk/HStss7"
    "Q8/5DqkGD1annQ+eoICo3oi0dITZ0Qll56Dowb8lXi6WHViVDdih/oeUwVJY89uJNtTW"
    "rz7t7QIDAQAB"
)
FIXED_MAC_ID_SEED = "abcd1234567890ef"
AUTH_HEADERS = {
    "app_version": "1.0.5",
    "sys_version": "17.2",
    "platform": "1",
    "User-Agent": (
        "DxPowerProject/1.0.5 (com.hb.jackery; build:2; iOS 17.2.0) Alamofire/5.8.0"
    ),
    "model": "iPad Pro (12.9-inch) (3rd generation)",
    "accept-language": "ja-JP",
}
ANDROID_APK_HEADERS = {
    "platform": "2",
    "app_version": "v1.0.7",
    "app_version_code": "107",
    "Accept-Language": "en",
    "sys_version": "Home Assistant",
    "device_model": "Home Assistant",
    "network": "wifi",
    "Content-Type": "application/x-www-form-urlencoded",
}
HEADER_PROFILES = {
    "ios_app_1_0_5": AUTH_HEADERS,
    "android_apk_1_0_7": ANDROID_APK_HEADERS,
}
PROBE_ENDPOINTS = (
    "/v1/device/property",
    "/v1/device/setting",
    "/v1/device/settings",
    "/v1/device/workingMode",
    "/v1/device/working_mode",
    "/v1/device/chargePlan",
    "/v1/device/charge_plan",
    "/v1/device/schedule",
    "/v1/device/timePlan",
    "/v1/device/time_plan",
    "/v1/device/mode",
    "/v1/device/config",
    "/v2/device/property",
    "/v2/device/setting",
    "/v2/device/settings",
    "/v2/device/workingMode",
    "/v2/device/working_mode",
    "/v2/device/chargePlan",
    "/v2/device/charge_plan",
    "/v2/device/schedule",
    "/v2/device/timePlan",
    "/v2/device/time_plan",
    "/v2/device/mode",
    "/v2/device/config",
)
PROPERTY_SNAPSHOT_PROFILES = ("ios_app_1_0_5", "android_apk_1_0_7")
EXTENDED_HEADER_PROFILES = ("ios_app_1_0_5", "android_apk_1_0_7")
EXTENDED_IDENTIFIER_NAMES = (
    "deviceId",
    "devId",
    "id",
    "deviceSn",
    "devSn",
    "sn",
    "deviceCode",
)
EXTENDED_PROBE_ENDPOINTS = (
    "/v1/device/property",
    "/v1/device/properties",
    "/v1/device/property/list",
    "/v1/device/setting",
    "/v1/device/settings",
    "/v1/device/config",
    "/v1/device/workingMode",
    "/v1/device/chargePlan",
    "/v1/device/chargePlan/detail",
    "/v1/device/chargePlan/info",
    "/v1/device/chargePlan/list",
    "/v1/device/chargePlan/page",
    "/v1/device/chargePlan/query",
    "/v1/device/chargePlan/status",
    "/v1/device/chargingPlan",
    "/v1/device/chargingPlan/detail",
    "/v1/device/chargingPlan/info",
    "/v1/device/chargingPlan/list",
    "/v1/device/chargingPlan/page",
    "/v1/device/chargingPlan/query",
    "/v1/device/chargingPlan/status",
    "/v1/device/charge_plan",
    "/v1/device/charging_plan",
    "/v1/device/getChargePlan",
    "/v1/device/queryChargePlan",
    "/v1/device/getChargingPlan",
    "/v1/device/queryChargingPlan",
    "/v1/device/charge/plan",
    "/v1/device/charge/schedule",
    "/v1/device/charge/timer",
    "/v1/device/charge/reserve",
    "/v1/device/charging/plan",
    "/v1/device/charging/schedule",
    "/v1/device/charging/timer",
    "/v1/device/reserveCharge",
    "/v1/device/reserve_charge",
    "/v1/device/appointment",
    "/v1/device/appointment/list",
    "/v1/device/appointment/detail",
    "/v1/device/schedule",
    "/v1/device/schedule/detail",
    "/v1/device/schedule/list",
    "/v1/device/timer",
    "/v1/device/timer/detail",
    "/v1/device/timer/list",
    "/v1/device/timePlan",
    "/v1/device/timePlan/detail",
    "/v1/device/timePlan/list",
    "/v1/device/time_plan/detail",
    "/v1/device/time_plan/list",
    "/v1/device/timing/list",
    "/v1/device/plan",
    "/v1/device/plan/detail",
    "/v1/device/plan/list",
    "/v1/device/powerPlan",
    "/v1/device/power_plan",
    "/v1/device/dp",
    "/v1/device/dp/list",
    "/v1/device/dps",
    "/v1/device/function/list",
    "/v1/device/function",
    "/v1/device/functions",
    "/v1/device/schema",
    "/v1/device/schema/list",
    "/v1/device/specification",
    "/v1/device/specifications",
    "/v1/device/status",
    "/v1/device/status/list",
    "/v1/device/instruction",
    "/v1/device/instructions",
)
READ_ONLY_POST_IDENTIFIER_NAMES = (
    "deviceId",
    "devId",
    "id",
    "deviceSn",
    "devSn",
    "sn",
    "deviceCode",
)
READ_ONLY_POST_HEADER_PROFILES = ("ios_app_1_0_5", "android_apk_1_0_7")
READ_ONLY_POST_BODY_FORMATS = ("form", "json")
READ_ONLY_POST_PROBE_ENDPOINTS = (
    "/v1/device/chargePlan",
    "/v1/device/chargePlan/detail",
    "/v1/device/chargePlan/info",
    "/v1/device/chargePlan/list",
    "/v1/device/chargePlan/page",
    "/v1/device/chargePlan/query",
    "/v1/device/chargePlan/status",
    "/v1/device/chargingPlan",
    "/v1/device/chargingPlan/detail",
    "/v1/device/chargingPlan/info",
    "/v1/device/chargingPlan/list",
    "/v1/device/chargingPlan/page",
    "/v1/device/chargingPlan/query",
    "/v1/device/chargingPlan/status",
    "/v1/device/charge_plan",
    "/v1/device/charging_plan",
    "/v1/device/getChargePlan",
    "/v1/device/queryChargePlan",
    "/v1/device/getChargingPlan",
    "/v1/device/queryChargingPlan",
    "/v1/device/charge/plan",
    "/v1/device/charge/schedule",
    "/v1/device/charge/timer",
    "/v1/device/charge/reserve",
    "/v1/device/charging/plan",
    "/v1/device/charging/schedule",
    "/v1/device/charging/timer",
    "/v1/device/reserveCharge",
    "/v1/device/reserve_charge",
    "/v1/device/appointment",
    "/v1/device/appointment/list",
    "/v1/device/appointment/detail",
    "/v1/device/schedule",
    "/v1/device/schedule/detail",
    "/v1/device/schedule/list",
    "/v1/device/timer",
    "/v1/device/timer/detail",
    "/v1/device/timer/list",
    "/v1/device/timePlan",
    "/v1/device/time_plan",
    "/v1/device/timePlan/detail",
    "/v1/device/timePlan/list",
    "/v1/device/time_plan/detail",
    "/v1/device/time_plan/list",
    "/v1/device/timing/list",
    "/v1/device/plan",
    "/v1/device/plan/detail",
    "/v1/device/plan/list",
    "/v1/device/powerPlan",
    "/v1/device/power_plan",
    "/v1/device/function/list",
    "/v1/device/schema",
    "/v1/device/specification",
    "/v1/device/status",
)
METHOD_DISCOVERY_METHODS = ("HEAD", "OPTIONS")
METHOD_DISCOVERY_ENDPOINTS = READ_ONLY_POST_PROBE_ENDPOINTS
TARGETED_PROPERTY_PROBE_ENDPOINTS = (
    "/v1/device/property",
    "/v1/device/properties",
    "/v1/device/dp",
    "/v1/device/dps",
    "/v1/device/status",
    "/v1/device/schema",
    "/v1/device/function",
    "/v1/device/function/list",
    "/v1/device/functions",
    "/v1/device/specification",
)
CHARGING_PLAN_PROPERTY_KEYS = ("107", "108")
CHARGING_PLAN_CODE_TERMS = (
    "charge_plan",
    "chargePlan",
    "charging_plan",
    "chargingPlan",
    "time_plan",
    "timePlan",
    "schedule",
    "timer",
)
PATH_TEMPLATE_PROBE_ENDPOINTS = (
    "/v1/device/{device_id}/property",
    "/v1/device/{device_id}/properties",
    "/v1/device/{device_id}/status",
    "/v1/device/{device_id}/setting",
    "/v1/device/{device_id}/settings",
    "/v1/device/{device_id}/config",
    "/v1/device/{device_id}/dp",
    "/v1/device/{device_id}/dps",
    "/v1/device/{device_id}/function",
    "/v1/device/{device_id}/functions",
    "/v1/device/{device_id}/function/list",
    "/v1/device/{device_id}/schema",
    "/v1/device/{device_id}/specification",
    "/v1/device/{device_id}/chargePlan",
    "/v1/device/{device_id}/chargePlan/detail",
    "/v1/device/{device_id}/chargePlan/list",
    "/v1/device/{device_id}/chargingPlan",
    "/v1/device/{device_id}/chargingPlan/detail",
    "/v1/device/{device_id}/chargingPlan/list",
    "/v1/device/{device_id}/charge_plan",
    "/v1/device/{device_id}/charging_plan",
    "/v1/device/{device_id}/charge/plan",
    "/v1/device/{device_id}/charge/schedule",
    "/v1/device/{device_id}/charge/timer",
    "/v1/device/{device_id}/charging/plan",
    "/v1/device/{device_id}/charging/schedule",
    "/v1/device/{device_id}/charging/timer",
    "/v1/device/{device_id}/schedule",
    "/v1/device/{device_id}/schedule/list",
    "/v1/device/{device_id}/timer",
    "/v1/device/{device_id}/timer/list",
    "/v1/device/{device_id}/timePlan",
    "/v1/device/{device_id}/timePlan/list",
    "/v1/device/{device_id}/plan",
    "/v1/device/{device_id}/plan/list",
    "/v1/devices/{device_id}/status",
    "/v1/devices/{device_id}/functions",
    "/v1/devices/{device_id}/schema",
    "/v1/devices/{device_id}/specification",
    "/v1/devices/{device_id}/chargePlan",
    "/v1/devices/{device_id}/chargingPlan",
)
TUYA_PATH_PROBE_ENDPOINTS = (
    "/v1.0/devices/{device_id}/status",
    "/v1.0/devices/{device_id}/functions",
    "/v1.0/iot-03/devices/{device_id}/specification",
    "/v1.0/iot-03/devices/{device_id}/specifications",
    "/v1.1/iot-03/devices/{device_id}/specification",
    "/v1.1/iot-03/devices/{device_id}/specifications",
    "/v1.0/iot-03/devices/{device_id}/status",
    "/v1.0/iot-03/devices/{device_id}/functions",
    "/v1.0/devices/{device_sn}/status",
    "/v1.0/devices/{device_code}/status",
)
TUYA_PRODUCT_PROBE_ENDPOINTS = (
    "/v1.0/products/{product_id}/functions",
    "/v1.0/products/{product_id}/schema",
    "/v1.0/products/{product_id}/specification",
    "/v1.0/iot-03/products/{product_id}/functions",
    "/v1.0/iot-03/products/{product_id}/schema",
    "/v1.0/iot-03/products/{product_id}/specification",
    "/v1.0/iot-03/products/{product_id}/specifications",
    "/v1.1/iot-03/products/{product_id}/functions",
    "/v1.1/iot-03/products/{product_id}/schema",
    "/v1.1/iot-03/products/{product_id}/specification",
    "/v1.1/iot-03/products/{product_id}/specifications",
)
TUYA_FINGERPRINT_FIELDS = (
    "bizType",
    "category",
    "categoryCode",
    "devId",
    "dpCode",
    "dpId",
    "dpName",
    "dps",
    "functions",
    "function",
    "localKey",
    "productId",
    "productKey",
    "product_id",
    "product_key",
    "schema",
    "schemaExt",
    "statusSet",
    "uid",
    "uuid",
)
TUYA_CHARGING_PLAN_TERMS = (
    "107",
    "108",
    "appointment",
    "appoint",
    "charge_plan",
    "chargeplan",
    "charging",
    "charging_plan",
    "dp107",
    "dp108",
    "off_peak",
    "offpeak",
    "reserve",
    "schedule",
    "sched",
    "timer",
    "time_plan",
    "timeplan",
)
SOURCE_SCAN_TERMS = (
    "107",
    "108",
    "appoint",
    "charge",
    "charging",
    "off_peak",
    "plan",
    "reserve",
    "schedule",
    "timer",
)
